export enum OrderStatusEnum {
  NEW_ORDER = 'NEW_ORDER',
  CANCEL = 'CANCEL',
  TAKEN_ORDER = 'TAKEN_ORDER',
  DELIVERING = 'DELIVERING',
  DELIVERED = 'DELIVERED',
  SINGED_RETURN = 'SINGED_RETURN',
  RETURNING_SHOP = 'RETURNING_SHOP',
  RETURNED_SHOP = 'RETURNED_SHOP',
  PAY_SHOP = 'PAY_SHOP',
  PAID_SHOP = 'PAID_SHOP',
}
