export enum TransactionTypeEnum {
  RECHARGE = 'RECHARGE',
  WITHDRAW_MONEY = 'WITHDRAW_MONEY',
  PAYMENT = 'PAYMENT',
  COURSE_PAYMENT = 'COURSE_PAYMENT',
  UPGRADE_TO_TEACHER = 'UPGRADE_TO_TEACHER',
  JOINS_CLASS = 'JOINS_CLASS',
}
