name: Deploy to DockerHub and VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: minhch/webontecoursebe:latest

      - name: Connect to VPS and update Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            docker stop ywebontecoursebe || true
            docker rm webontecoursebe || true
            docker pull minhch/webontecoursebe:latest
            docker run -d --name webontecoursebe minhch/webontecoursebe:latest
